
export interface Translations {
  // Project Lable
  title: string,
  // LIC: string,

  // Navigation
  home: string;
  addRecord: string;
  viewRecords: string;
  login: string;
  signup: string;
  signupFree: string;
  logout: string;
  profile: string;  
  referral: string;  
  aboutUs: string;
  ourPlans: string;

  otherLinks: string;
  currentMonthDue: string;
  nextMonthDue: string;
  missedPayments: string;
  bestInfoHub: string;
  quickLinks: string;

  contactInfo: string;
  officeAddress: string;

  features: string,
  securePolicyManagement: string,
  multiLanguageSupport: string,
  userAuthentication: string,
  dataExportImport: string,
  searchFilterRecords: string,
  realTimeUpdates: string,

  aboutCompany: string;
  companyDescription: string;
  allRightsReserved: string;
  footerTagline: string;

  // Common
  welcome: string;
  welcomeBack: string;
  name: string;
  email: string;
  password: string;
  confirmPassword: string;
  SelectSubscriptionPlan: string;
  ReferralCode: string;
  validate: string;
  Optional: string;
  submit: string;
  cancel: string;
  save: string;
  delete: string;
  edit: string;
  view: string;
  search: string;
  loading: string;
  profileInformation: string;
  quickStatistics: string;
  daysActive: string;
  accountType: string;
  dataSecurity: string;
  
  // Auth
  loginTitle: string;
  signupTitle: string;
  userId: string;
  fullAddress: string;
  mobileNumber: string;
  designation: string;
  createAccount: string;

  referralDiscountNote1: string;
  referralDiscountNote2: string;
  referralDiscountNote3: string;
  referralDiscountNote4: string;
  referralDiscountNote5: string;
  referralDiscountNote6: string;

  makePaymentCreateAccount: string;
  alreadyHaveAccount: string;
  dontHaveAccount: string;
  loginSuccess: string;
  signupSuccess: string;
  invalidCredentials: string;
  userExists: string;
  
  // Forms
  policyDetails: string;
  personalInformation: string;
  familyInformation: string;
  beneficiaryInformation: string;
  
  // Test credentials
  testCredentials: string;
  testUserId: string;
  testPassword: string;
  
  // Records
  loadingRecords: string;
  totalRecords: string;
  noRecords: string;
  recordDetails: string;
  filteredRecords: string;
  addNewRecord: string;
  allRecord: string;
  viewAllRecords: string;
  duePaymentNoRecordNote: string;
  nextMonthDuePaymentNoRecordNote: string;
  missedPaymentNoRecordNote: string;
  
  // Generated IDs
  autoGeneratedId: string;
  easyRememberId: string;
}
export type Language = 'en' | 'hi';
