import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { UserPlus } from "lucide-react";
import { generateAutoUserId, generateEasyUserId, generateReferralCode, saveUser, User } from "@/utils/auth";
import { useLanguage } from "@/hooks/useLanguage";
import { useToast } from "@/hooks/use-toast";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";

const SignUp = () => {
  const [formData, setFormData] = useState({
    name: "",
    fullAddress: "",
    mobileNumber: "",
    designation: "",
    email: "",
    password: "",
    confirmPassword: "",
    selectedPlan: "",
    referralCode: ""
  });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [generatedIds, setGeneratedIds] = useState<{autoId: string, easyId: string} | null>(null);
  
  const navigate = useNavigate();
  const { t } = useLanguage();
  const { toast } = useToast();

  const plans = [
    { id: '6months', name: '6 Months Plan', price: 599, originalPrice: 899 },
    { id: '12months', name: '12 Months Plan', price: 1099, originalPrice: 1599 },
    { id: '24months', name: '24 Months Plan', price: 2099, originalPrice: 2999 }
  ];

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    
    // Generate preview IDs when user types name, mobile, or address
    if ((name === 'name' || name === 'mobileNumber' || name === 'fullAddress') && 
        formData.name && formData.mobileNumber && formData.fullAddress) {
      const autoId = generateAutoUserId();
      const easyId = generateEasyUserId(
        name === 'name' ? value : formData.name,
        name === 'mobileNumber' ? value : formData.mobileNumber,
        name === 'fullAddress' ? value : formData.fullAddress
      );
      setGeneratedIds({ autoId, easyId });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    // Validation
    if (formData.password !== formData.confirmPassword) {
      setError("Passwords do not match");
      setIsLoading(false);
      return;
    }

    if (formData.mobileNumber.length !== 10) {
      setError("Mobile number must be 10 digits");
      setIsLoading(false);
      return;
    }

    if (!formData.selectedPlan) {
      setError("Please select a subscription plan");
      setIsLoading(false);
      return;
    }

    try {
      const autoId = generateAutoUserId();
      const easyId = generateEasyUserId(formData.name, formData.mobileNumber, formData.fullAddress);
      const userReferralCode = generateReferralCode(formData.name, autoId);

      const selectedPlanData = plans.find(plan => plan.id === formData.selectedPlan);
      const planDurationMonths = parseInt(formData.selectedPlan.replace('months', ''));
      
      const newUser: User = {
        id: autoId,
        easyId: easyId,
        name: formData.name,
        fullAddress: formData.fullAddress,
        mobileNumber: formData.mobileNumber,
        designation: formData.designation,
        email: formData.email,
        password: formData.password,
        createdAt: new Date().toISOString(),
        referralCode: userReferralCode,
        referredBy: formData.referralCode || undefined,
        subscription: selectedPlanData ? {
          planId: selectedPlanData.id,
          duration: selectedPlanData.name,
          price: selectedPlanData.price,
          startDate: new Date().toISOString(),
          endDate: new Date(Date.now() + (planDurationMonths * 30 * 24 * 60 * 60 * 1000)).toISOString(),
          status: 'active' as const
        } : undefined
      };

      const success = saveUser(newUser);
      
      if (success) {
        toast({
          title: t('signupSuccess'),
          description: `${t('autoGeneratedId')}: ${autoId}\n${t('easyRememberId')}: ${easyId}\nReferral Code: ${userReferralCode}`,
        });
        navigate("/login");
      } else {
        setError(t('userExists'));
      }
    } catch (err) {
      setError("Failed to create account. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-muted/30 flex items-center justify-center p-4">
      <div className="w-full max-w-2xl space-y-6">
        <div className="flex justify-end">
          <LanguageSwitcher />
        </div>
        
        <Card>
          <CardHeader className="text-center">
            <div className="w-16 h-16 bg-primary rounded-full flex items-center justify-center mx-auto mb-4">
              <UserPlus className="w-8 h-8 text-primary-foreground" />
            </div>
            <CardTitle className="text-2xl text-form-header">{t('signupTitle')}</CardTitle>
            <CardDescription>
              Life Insurance Corporation - {t('createAccount')}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="name">{t('name')} *</Label>
                  <Input
                    id="name"
                    name="name"
                    type="text"
                    placeholder={t('name')}
                    value={formData.name}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="mobileNumber">{t('mobileNumber')} *</Label>
                  <Input
                    id="mobileNumber"
                    name="mobileNumber"
                    type="tel"
                    placeholder="10-digit mobile number"
                    value={formData.mobileNumber}
                    onChange={handleInputChange}
                    pattern="[0-9]{10}"
                    maxLength={10}
                    required
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="fullAddress">{t('fullAddress')} *</Label>
                <Input
                  id="fullAddress"
                  name="fullAddress"
                  type="text"
                  placeholder={t('fullAddress')}
                  value={formData.fullAddress}
                  onChange={handleInputChange}
                  required
                />
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="designation">{t('designation')} *</Label>
                  <Input
                    id="designation"
                    name="designation"
                    type="text"
                    placeholder={t('designation')}
                    value={formData.designation}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="email">{t('email')} *</Label>
                  <Input
                    id="email"
                    name="email"
                    type="email"
                    placeholder={t('email')}
                    value={formData.email}
                    onChange={handleInputChange}
                    required
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="password">{t('password')} *</Label>
                  <Input
                    id="password"
                    name="password"
                    type="password"
                    placeholder={t('password')}
                    value={formData.password}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="confirmPassword">{t('confirmPassword')} *</Label>
                  <Input
                    id="confirmPassword"
                    name="confirmPassword"
                    type="password"
                    placeholder={t('confirmPassword')}
                    value={formData.confirmPassword}
                    onChange={handleInputChange}
                    required
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="selectedPlan">{t('SelectSubscriptionPlan')} *</Label>
                  <Select 
                    value={formData.selectedPlan} 
                    onValueChange={(value) => setFormData({ ...formData, selectedPlan: value })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder={t('SelectSubscriptionPlan')} />
                    </SelectTrigger>
                    <SelectContent>
                      {plans.map((plan) => (
                        <SelectItem key={plan.id} value={plan.id}>
                          <div className="flex items-center justify-between w-full">
                            <span>{plan.name}</span>
                            <div className="flex items-center gap-2 ml-4">
                              <Badge variant="outline">₹{plan.price}</Badge>
                              {plan.originalPrice && (
                                <span className="text-xs text-muted-foreground line-through">₹{plan.originalPrice}</span>
                              )}
                            </div>
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  {/* <Label htmlFor="referralCode">Referral Code (Optional)</Label> */}
                  {/* <Label htmlFor="referralCode">{t('ReferralCodeOptional')}</Label> */}
                  <Label htmlFor="referralCode">{t('ReferralCode')+' ('+t('Optional')+')'}</Label>
                  <Input
                    id="referralCode"
                    name="referralCode"
                    type="text"
                    placeholder={t('ReferralCode')+' ('+t('Optional')+')'}
                    value={formData.referralCode}
                    onChange={(e) => setFormData({ ...formData, referralCode: e.target.value.toUpperCase() })}
                  />
                </div>
              </div>

              {/* Preview Generated IDs */}
              {generatedIds && (
                <Card className="bg-accent/50">
                  <CardHeader className="pb-2">
                    <CardTitle className="text-sm text-form-subheader">Generated User IDs (Preview)</CardTitle>
                  </CardHeader>
                  <CardContent className="text-xs space-y-1">
                    <p><strong>{t('autoGeneratedId')}:</strong> {generatedIds.autoId}</p>
                    <p><strong>{t('easyRememberId')}:</strong> {generatedIds.easyId}</p>
                  </CardContent>
                </Card>
              )}

              {error && (
                <Alert variant="destructive">
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}

              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? t('loading') : t('createAccount')}
              </Button>
            </form>

            <div className="text-center">
              <p className="text-sm text-muted-foreground">
                {t('alreadyHaveAccount')}{" "}
                <Link to="/login" className="text-primary hover:underline">
                  {t('login')}
                </Link>
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default SignUp;