// Multilingual support for English and Hindi

export interface Translations {
  // Navigation
  home: string;
  addRecord: string;
  viewRecords: string;
  login: string;
  signup: string;
  logout: string;
  
  // Common
  welcome: string;
  name: string;
  email: string;
  password: string;
  confirmPassword: string;
  submit: string;
  cancel: string;
  save: string;
  delete: string;
  edit: string;
  view: string;
  search: string;
  loading: string;
  
  // Auth
  loginTitle: string;
  signupTitle: string;
  userId: string;
  fullAddress: string;
  mobileNumber: string;
  designation: string;
  createAccount: string;
  alreadyHaveAccount: string;
  dontHaveAccount: string;
  loginSuccess: string;
  signupSuccess: string;
  invalidCredentials: string;
  userExists: string;
  
  // Forms
  policyDetails: string;
  personalInformation: string;
  familyInformation: string;
  beneficiaryInformation: string;
  
  // Test credentials
  testCredentials: string;
  testUserId: string;
  testPassword: string;
  
  // Records
  totalRecords: string;
  noRecords: string;
  recordDetails: string;
  
  // Generated IDs
  autoGeneratedId: string;
  easyRememberId: string;
}

export const translations: Record<string, Translations> = {
  en: {
    // Navigation
    home: "Home",
    addRecord: "Add Record",
    viewRecords: "View Records",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    
    // Common
    welcome: "Welcome",
    name: "Name",
    email: "Email ID",
    password: "Password",
    confirmPassword: "Confirm Password",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    search: "Search",
    loading: "Loading...",
    
    // Auth
    loginTitle: "Login to Your Account",
    signupTitle: "Create New Account",
    userId: "User ID",
    fullAddress: "Full Address",
    mobileNumber: "Mobile Number",
    designation: "Designation",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    loginSuccess: "Login successful!",
    signupSuccess: "Account created successfully!",
    invalidCredentials: "Invalid User ID or Password",
    userExists: "User with this email or mobile already exists",
    
    // Forms
    policyDetails: "Policy Details",
    personalInformation: "Personal Information",
    familyInformation: "Family Information",
    beneficiaryInformation: "Beneficiary Information",
    
    // Test credentials
    testCredentials: "Test Credentials",
    testUserId: "User ID: UID123456 or test123demo",
    testPassword: "Password: test123",
    
    // Records
    totalRecords: "Total Records",
    noRecords: "No records found",
    recordDetails: "Record Details",
    
    // Generated IDs
    autoGeneratedId: "Auto-generated User ID",
    easyRememberId: "Easy-to-remember User ID"
  },
  
  hi: {
    // Navigation
    home: "मुख्य पृष्ठ",
    addRecord: "रिकॉर्ड जोड़ें",
    viewRecords: "रिकॉर्ड देखें",
    login: "लॉग इन",
    signup: "साइन अप",
    logout: "लॉग आउट",
    
    // Common
    welcome: "स्वागत",
    name: "नाम",
    email: "ईमेल आईडी",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    submit: "जमा करें",
    cancel: "रद्द करें",
    save: "सेव करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    view: "देखें",
    search: "खोजें",
    loading: "लोड हो रहा है...",
    
    // Auth
    loginTitle: "अपने खाते में लॉग इन करें",
    signupTitle: "नया खाता बनाएं",
    userId: "यूजर आईडी",
    fullAddress: "पूरा पता",
    mobileNumber: "मोबाइल नंबर",
    designation: "पदनाम",
    createAccount: "खाता बनाएं",
    alreadyHaveAccount: "पहले से खाता है?",
    dontHaveAccount: "खाता नहीं है?",
    loginSuccess: "लॉग इन सफल!",
    signupSuccess: "खाता सफलतापूर्वक बनाया गया!",
    invalidCredentials: "गलत यूजर आईडी या पासवर्ड",
    userExists: "इस ईमेल या मोबाइल का उपयोगकर्ता पहले से मौजूद है",
    
    // Forms
    policyDetails: "पॉलिसी विवरण",
    personalInformation: "व्यक्तिगत जानकारी",
    familyInformation: "पारिवारिक जानकारी",
    beneficiaryInformation: "लाभार्थी की जानकारी",
    
    // Test credentials
    testCredentials: "परीक्षण प्रमाण पत्र",
    testUserId: "यूजर आईडी: UID123456 या test123demo",
    testPassword: "पासवर्ड: test123",
    
    // Records
    totalRecords: "कुल रिकॉर्ड",
    noRecords: "कोई रिकॉर्ड नहीं मिला",
    recordDetails: "रिकॉर्ड विवरण",
    
    // Generated IDs
    autoGeneratedId: "स्वतः उत्पन्न यूजर आईडी",
    easyRememberId: "याद रखने में आसान यूजर आईडी"
  }
};

export type Language = 'en' | 'hi';

export const getTranslation = (lang: Language, key: keyof Translations): string => {
  return translations[lang][key] || translations.en[key] || key;
};

// Language context
export const getStoredLanguage = (): Language => {
  const stored = localStorage.getItem('language') as Language;
  return stored && translations[stored] ? stored : 'en';
};

export const setStoredLanguage = (lang: Language): void => {
  localStorage.setItem('language', lang);
};