// Multilingual support for English and Hindi

export interface Translations {
  // Project Lable
  title: string,
  // LIC: string,

  // Navigation
  home: string;
  addRecord: string;
  viewRecords: string;
  login: string;
  signup: string;
  logout: string;
  profile: string;  
  referral: string;  
  aboutUs: string;
  ourPlans: string;

  otherLinks: string;
  currentMonthDue: string;
  bestInfoHub: string;
  quickLinks: string;

  contactInfo: string;
  officeAddress: string;

  features: string,
  securePolicyManagement: string,
  multiLanguageSupport: string,
  userAuthentication: string,
  dataExportImport: string,
  searchFilterRecords: string,
  realTimeUpdates: string,

  aboutCompany: string;
  companyDescription: string;
  allRightsReserved: string;

  // Common
  welcome: string;
  welcomeBack: string;
  name: string;
  email: string;
  password: string;
  confirmPassword: string;
  SelectSubscriptionPlan: string;
  ReferralCode: string;
  validate: string;
  Optional: string;
  submit: string;
  cancel: string;
  save: string;
  delete: string;
  edit: string;
  view: string;
  search: string;
  loading: string;
  profileInformation: string;
  quickStatistics: string;
  daysActive: string;
  accountType: string;
  dataSecurity: string;
  
  // Auth
  loginTitle: string;
  signupTitle: string;
  userId: string;
  fullAddress: string;
  mobileNumber: string;
  designation: string;
  createAccount: string;
  makePaymentCreateAccount: string;
  alreadyHaveAccount: string;
  dontHaveAccount: string;
  loginSuccess: string;
  signupSuccess: string;
  invalidCredentials: string;
  userExists: string;
  
  // Forms
  policyDetails: string;
  personalInformation: string;
  familyInformation: string;
  beneficiaryInformation: string;
  
  // Test credentials
  testCredentials: string;
  testUserId: string;
  testPassword: string;
  
  // Records
  loadingRecords: string;
  totalRecords: string;
  noRecords: string;
  recordDetails: string;
  filteredRecords: string;
  addNewRecord: string;
  allRecord: string;
  viewAllRecords: string;
  
  // Generated IDs
  autoGeneratedId: string;
  easyRememberId: string;
}

export const translations: Record<string, Translations> = {
  en: {
    // Project Lable
    title: "LIC Agent Dairy",
    // LIC: "Life Insurance Corporation of India",

    // Navigation
    home: "Home",
    addRecord: "Add Record",
    viewRecords: "View Records",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    profile: "Profile",
    referral: "Referral",
    aboutUs: "About Us",
    ourPlans: "Our Plans",

    otherLinks: "Other Links",
    currentMonthDue: "Current Month Due",
    bestInfoHub: "Best Info Hub",
    quickLinks: "Quick Links",

    contactInfo: "Contact Info",
    officeAddress: "No. 170, Sector 39, Gurugram Haryana, Bharat - 122022",
    
    features: "Features",
    securePolicyManagement: "Secure Policy Management",
    multiLanguageSupport: "Multi-Language Support",
    userAuthentication: "User Authentication",
    dataExportImport: "Data Export & Import",
    searchFilterRecords: "Search & Filter Records",
    realTimeUpdates: "Real-Time Updates",

    aboutCompany: "About Company",
    companyDescription: "Your trusted partner for all type insurance policy management. Secure, reliable, and user-friendly platform for all your policy needs.",
    allRightsReserved: "All Rights Reserved",
    
    // Common
    welcome: "Welcome",
    welcomeBack: "Welcome Back",
    name: "Name",
    email: "Email ID",
    password: "Password",
    confirmPassword: "Confirm Password",
    SelectSubscriptionPlan: "Select Subscription Plan",
    ReferralCode: "Referral Code",
    validate: "Validate",
    Optional: "Optional",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    search: "Search",
    loading: "Loading...",
    profileInformation: "Profile Information",
    quickStatistics: "Quick Statistics",
    daysActive: "Days Active",
    accountType: "Account Type",
    dataSecurity: "Data Security",
    
    // Auth
    loginTitle: "Login to Your Account",
    signupTitle: "Create New Account",
    userId: "User ID",
    fullAddress: "Full Address",
    mobileNumber: "Mobile Number",
    designation: "Designation",
    createAccount: "Create Account",
    makePaymentCreateAccount: "Make Payment & Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    loginSuccess: "Login successful!",
    signupSuccess: "Account created successfully!",
    invalidCredentials: "Invalid User ID or Password",
    userExists: "User with this email or mobile already exists",
    
    // Forms
    policyDetails: "Policy Details",
    personalInformation: "Personal Information",
    familyInformation: "Family Information",
    beneficiaryInformation: "Beneficiary Information",
    
    // Test credentials
    testCredentials: "Test Credentials",
    testUserId: "User ID: UID123456 or test123demo",
    testPassword: "Password: test123",
    
    // Records
    loadingRecords: "Loading Records...",
    totalRecords: "Total Records",
    noRecords: "No records found",
    recordDetails: "Record Details",
    filteredRecords: "Filtered Records",
    addNewRecord: "Add New Record",
    allRecord: "All Record",
    viewAllRecords: "View All Records",
    
    // Generated IDs
    autoGeneratedId: "Auto-generated User ID",
    easyRememberId: "Easy-to-remember User ID"
  },
  
  hi: {
    // Project Lable
    // title: "एलआईसी एजेंट डायरी",
    title: "एलआईसी अभिकर्ता डायरी",
    // LIC: "भारतीय जीवन बीमा निगम",

    // Navigation
    home: "मुख्य पृष्ठ",
    addRecord: "रिकॉर्ड जोड़ें",
    viewRecords: "रिकॉर्ड देखें",
    login: "लॉग इन",
    // signup: "साइन अप",
    signup: "खाता बनाएं",
    logout: "लॉग आउट",
    profile: "प्रोफ़ाइल",
    referral: "रेफ़रल",
    aboutUs: "हमारे बारे में",
    ourPlans: "हमारे प्लान",

    otherLinks: "अन्य लिंक",
    currentMonthDue: "इस महीने का बकाया",
    bestInfoHub: "ज्ञान बढ़ाएँ",
    quickLinks: "मुख्य लिंक",

    contactInfo: "संपर्क जानकारी",
    officeAddress: "संख्या 170, सेक्टर 39, गुरुग्राम हरियाणा, भारत – 122022",

    features: "विशेषताएँ",
    securePolicyManagement: "सुरक्षित पॉलिसी प्रबंधन",
    multiLanguageSupport: "बहुभाषी समर्थन",
    userAuthentication: "उपयोगकर्ता प्रमाणीकरण",
    dataExportImport: "डेटा निर्यात और आयात",
    searchFilterRecords: "रिकॉर्ड खोजें और फ़िल्टर करें",
    realTimeUpdates: "रीयल-टाइम अपडेट्स",

    aboutCompany: "कंपनी के बारे में",
    companyDescription: "आपका भरोसेमंद साथी सभी बीमा पॉलिसियों के प्रबंधन में। सुरक्षित, आसान और विश्वसनीय प्लेटफ़ॉर्म जो आपकी हर पॉलिसी जरूरत को पूरा करता है।",
    allRightsReserved: "सभी अधिकार सुरक्षित हैं।",
    
    // Common
    welcome: "स्वागत",
    welcomeBack: "फिर से स्वागत है",
    name: "नाम",
    email: "ईमेल आईडी",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    SelectSubscriptionPlan:"सदस्यता योजना चुनें",
    ReferralCode:"रेफरल कोड",
    validate:"सत्यापित करें",
    Optional:"वैकल्पिक",
    submit: "जमा करें",
    cancel: "रद्द करें",
    save: "सेव करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    view: "देखें",
    search: "खोजें",
    loading: "लोड हो रहा है...",
    profileInformation: "प्रोफ़ाइल जानकारी",
    quickStatistics: "संक्षिप्त आंकड़े",
    daysActive: "सक्रिय दिन",
    accountType: "खाता प्रकार",
    dataSecurity: "डेटा सुरक्षा",
    
    // Auth
    loginTitle: "अपने खाते में लॉग इन करें",
    signupTitle: "नया खाता बनाएं",
    userId: "यूजर आईडी",
    fullAddress: "पूरा पता",
    mobileNumber: "मोबाइल नंबर",
    designation: "पदनाम",
    createAccount: "खाता बनाएं",
    makePaymentCreateAccount: "भुगतान करें और खाता बनाएं",
    alreadyHaveAccount: "पहले से खाता है?",
    dontHaveAccount: "खाता नहीं है?",
    loginSuccess: "लॉग इन सफल!",
    signupSuccess: "खाता सफलतापूर्वक बनाया गया!",
    invalidCredentials: "गलत यूजर आईडी या पासवर्ड",
    userExists: "इस ईमेल या मोबाइल का उपयोगकर्ता पहले से मौजूद है",
    
    // Forms
    policyDetails: "पॉलिसी विवरण",
    personalInformation: "व्यक्तिगत जानकारी",
    familyInformation: "पारिवारिक जानकारी",
    beneficiaryInformation: "लाभार्थी की जानकारी",
    
    // Test credentials
    testCredentials: "परीक्षण प्रमाण पत्र",
    testUserId: "यूजर आईडी: UID123456 या test123demo",
    testPassword: "पासवर्ड: test123",
    
    // Records
    loadingRecords: "रिकॉर्ड लोड हो रहे हैं...",
    totalRecords: "कुल रिकॉर्ड",
    noRecords: "कोई रिकॉर्ड नहीं मिला",
    recordDetails: "रिकॉर्ड विवरण",
    filteredRecords: "फ़िल्टर किए गए रिकॉर्ड",
    addNewRecord: "नया रिकॉर्ड जोड़ें",
    allRecord: "सभी रिकॉर्ड",
    viewAllRecords: "सभी रिकॉर्ड देखें",
    
    // Generated IDs
    autoGeneratedId: "स्वतः उत्पन्न यूजर आईडी",
    easyRememberId: "याद रखने में आसान यूजर आईडी"
  }
};

export type Language = 'en' | 'hi';

export const getTranslation = (lang: Language, key: keyof Translations): string => {
  return translations[lang][key] || translations.en[key] || key;
};

// Language context
export const getStoredLanguage = (): Language => {
  const stored = localStorage.getItem('language') as Language;
  return stored && translations[stored] ? stored : 'en';
};

export const setStoredLanguage = (lang: Language): void => {
  localStorage.setItem('language', lang);
};