import type { Translations, Language } from "@/types/utils/translations.types";
// Multilingual support for English and Hindi
export const translations: Record<string, Translations> = {
  en: {
    // Project Lable
    title: "LIC Agent Dairy",
    // LIC: "Life Insurance Corporation of India",

    // Navigation
    home: "Home",
    addRecord: "Add Record",
    viewRecords: "View Records",
    login: "Login",
    signup: "Sign Up",
    signupFree: "Sign up Free",
    logout: "Logout",
    profile: "Profile",
    referral: "Referral",
    aboutUs: "About Us",
    ourPlans: "Our Plans",

    otherLinks: "Other Links",
    currentMonthDue: "Current Month Due",
    nextMonthDue: "Next Month Due",
    missedPayments: "Missed Payments",
    bestInfoHub: "Best Info Hub",
    quickLinks: "Quick Links",

    contactInfo: "Contact Info",
    officeAddress: "No. 170, Sector 39, Gurugram Haryana, Bharat - 122022",
    
    features: "Features",
    securePolicyManagement: "Secure Policy Management",
    multiLanguageSupport: "Multi-Language Support",
    userAuthentication: "User Authentication",
    dataExportImport: "Data Export & Import",
    searchFilterRecords: "Search & Filter Records",
    realTimeUpdates: "Real-Time Updates",

    aboutCompany: "About Company",
    companyDescription: "Your trusted partner for all type insurance policy management. Secure, reliable, and user-friendly platform for all your policy needs.",
    allRightsReserved: "All Rights Reserved",
    footerTagline: "Every policy tracked by you. Every due date remembered. Every day.",
    
    // Common
    welcome: "Welcome",
    welcomeBack: "Welcome Back",
    name: "Name",
    email: "Email ID",
    password: "Password",
    confirmPassword: "Confirm Password",
    SelectSubscriptionPlan: "Select Subscription Plan",
    ReferralCode: "Referral Code",
    validate: "Validate",
    Optional: "Optional",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    search: "Search",
    loading: "Loading...",
    profileInformation: "Profile Information",
    quickStatistics: "Quick Statistics",
    daysActive: "Days Active",
    accountType: "Account Type",
    dataSecurity: "Data Security",
    
    // Auth
    loginTitle: "Login to Your Account",
    signupTitle: "Create New Account",
    userId: "User ID",
    fullAddress: "Full Address",
    mobileNumber: "Mobile Number",
    designation: "Designation",
    createAccount: "Create Account",

    referralDiscountNote1: "💰 Enter a valid",
    referralDiscountNote2: "Referral Code",
    referralDiscountNote3: "and get an instant",
    referralDiscountNote4: " ",
    referralDiscountNote5: "discount",
    referralDiscountNote6: "on any paid subscription plan.",

    makePaymentCreateAccount: "Make Payment & Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    loginSuccess: "Login successful!",
    signupSuccess: "Account created successfully!",
    invalidCredentials: "Invalid User ID or Password",
    userExists: "User with this email or mobile already exists",
    
    // Forms
    policyDetails: "Policy Details",
    personalInformation: "Personal Information",
    familyInformation: "Family Information",
    beneficiaryInformation: "Beneficiary Information",
    
    // Test credentials
    testCredentials: "Test Credentials",
    testUserId: "User ID: UID123456 or test123demo",
    testPassword: "Password: test123",
    
    // Records
    loadingRecords: "Loading Records...",
    totalRecords: "Total Records",
    noRecords: "No records found",
    recordDetails: "Record Details",
    filteredRecords: "Filtered Records",
    addNewRecord: "Add New Record",
    allRecord: "All Records",
    viewAllRecords: "View All Records",
    duePaymentNoRecordNote: "Not a single record has payment due this month! Great job!",
    nextMonthDuePaymentNoRecordNote: "Not a single record has payment due next month!",
    missedPaymentNoRecordNote: "Great, no records found! All previous payments are up to date.",
    
    // Generated IDs
    autoGeneratedId: "Auto-generated User ID",
    easyRememberId: "Easy-to-remember User ID"
  },
  
  hi: {
    // Project Lable
    // title: "एलआईसी एजेंट डायरी",
    title: "एलआईसी अभिकर्ता डायरी",
    // LIC: "भारतीय जीवन बीमा निगम",

    // Navigation
    home: "मुख्य पृष्ठ",
    addRecord: "रिकॉर्ड जोड़ें",
    viewRecords: "रिकॉर्ड देखें",
    login: "लॉग इन",
    signup: "खाता बनाएं",
    signupFree: "मुफ़्त में खाता बनाएं",
    logout: "लॉग आउट",
    profile: "प्रोफ़ाइल",
    referral: "रेफ़रल",
    aboutUs: "हमारे बारे में",
    ourPlans: "हमारे प्लान",

    otherLinks: "अन्य लिंक",
    currentMonthDue: "इस महीने का बकाया",
    nextMonthDue: "अगले महीने का बकाया",
    missedPayments: "मिस्ड पेमेंट्स",
    bestInfoHub: "ज्ञान बढ़ाएँ",
    quickLinks: "मुख्य लिंक",

    contactInfo: "संपर्क जानकारी",
    officeAddress: "संख्या 170, सेक्टर 39, गुरुग्राम हरियाणा, भारत – 122022",

    features: "विशेषताएँ",
    securePolicyManagement: "सुरक्षित पॉलिसी प्रबंधन",
    multiLanguageSupport: "बहुभाषी समर्थन",
    userAuthentication: "उपयोगकर्ता प्रमाणीकरण",
    dataExportImport: "डेटा निर्यात और आयात",
    searchFilterRecords: "रिकॉर्ड खोजें और फ़िल्टर करें",
    realTimeUpdates: "रीयल-टाइम अपडेट्स",

    aboutCompany: "कंपनी के बारे में",
    companyDescription: "आपका भरोसेमंद साथी सभी बीमा पॉलिसियों के प्रबंधन में। सुरक्षित, आसान और विश्वसनीय प्लेटफ़ॉर्म जो आपकी हर पॉलिसी जरूरत को पूरा करता है।",
    allRightsReserved: "सभी अधिकार सुरक्षित हैं।",
    footerTagline: "हर पॉलिसी पर आपकी नज़र, हर ड्यू डेट याद — हर दिन।",
    
    // Common
    welcome: "स्वागत",
    welcomeBack: "फिर से स्वागत है",
    name: "नाम",
    email: "ईमेल आईडी",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    SelectSubscriptionPlan:"सदस्यता योजना चुनें",
    ReferralCode:"रेफरल कोड",
    validate:"सत्यापित करें",
    Optional:"वैकल्पिक",
    submit: "जमा करें",
    cancel: "रद्द करें",
    save: "सेव करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    view: "देखें",
    search: "खोजें",
    loading: "लोड हो रहा है...",
    profileInformation: "प्रोफ़ाइल जानकारी",
    quickStatistics: "संक्षिप्त आंकड़े",
    daysActive: "सक्रिय दिन",
    accountType: "खाता प्रकार",
    dataSecurity: "डेटा सुरक्षा",
    
    // Auth
    loginTitle: "अपने खाते में लॉग इन करें",
    signupTitle: "नया खाता बनाएं",
    userId: "यूजर आईडी",
    fullAddress: "पूरा पता",
    mobileNumber: "मोबाइल नंबर",
    designation: "पदनाम",
    createAccount: "खाता बनाएं",
    
    referralDiscountNote1: "💰 एक मान्य",
    referralDiscountNote2: "रेफ़रल कोड",
    referralDiscountNote3: "दर्ज करें और किसी भी पेड सब्सक्रिप्शन प्लान पर तुरंत",
    referralDiscountNote4: "",
    referralDiscountNote5: "की छूट पाएं।",
    referralDiscountNote6: " ",

    makePaymentCreateAccount: "भुगतान करें और खाता बनाएं",
    alreadyHaveAccount: "पहले से खाता है?",
    dontHaveAccount: "खाता नहीं है?",
    loginSuccess: "लॉग इन सफल!",
    signupSuccess: "खाता सफलतापूर्वक बनाया गया!",
    invalidCredentials: "गलत यूजर आईडी या पासवर्ड",
    userExists: "इस ईमेल या मोबाइल का उपयोगकर्ता पहले से मौजूद है",
    
    // Forms
    policyDetails: "पॉलिसी विवरण",
    personalInformation: "व्यक्तिगत जानकारी",
    familyInformation: "पारिवारिक जानकारी",
    beneficiaryInformation: "लाभार्थी की जानकारी",
    
    // Test credentials
    testCredentials: "परीक्षण प्रमाण पत्र",
    testUserId: "यूजर आईडी: UID123456 या test123demo",
    testPassword: "पासवर्ड: test123",
    
    // Records
    loadingRecords: "रिकॉर्ड लोड हो रहे हैं...",
    totalRecords: "कुल रिकॉर्ड",
    noRecords: "कोई रिकॉर्ड नहीं मिला",
    recordDetails: "रिकॉर्ड विवरण",
    filteredRecords: "फ़िल्टर किए गए रिकॉर्ड",
    addNewRecord: "नया रिकॉर्ड जोड़ें",
    allRecord: "सभी रिकॉर्ड",
    viewAllRecords: "सभी रिकॉर्ड देखें",
    duePaymentNoRecordNote: "इस महीने किसी भी रिकॉर्ड का भुगतान बकाया नहीं है! बहुत बढ़िया!",
    nextMonthDuePaymentNoRecordNote: "अगले महीने किसी भी रिकॉर्ड का भुगतान बकाया नहीं है!",
    missedPaymentNoRecordNote: "शानदार, कोई रिकॉर्ड नहीं मिला! सभी पिछली भुगतान राशि समय पर चुकाई जा चुकी है।",
    
    // Generated IDs
    autoGeneratedId: "स्वतः उत्पन्न यूजर आईडी",
    easyRememberId: "याद रखने में आसान यूजर आईडी"
  }
};
export const getTranslation = (lang: Language, key: keyof Translations): string => {
  return translations[lang][key] || translations.en[key] || key;
};

// Language context
export const getStoredLanguage = (): Language => {
  const stored = localStorage.getItem('language') as Language;
  return stored && translations[stored] ? stored : 'en';
};

export const setStoredLanguage = (lang: Language): void => {
  localStorage.setItem('language', lang);
};